#!/usr/local/bin/python3.7

import os
import pkg_resources

dist = pkg_resources.get_distribution('pybitmessage')
script_file = os.path.join(dist.location, dist.key, 'bitmessagemain.py')
new_globals = globals()
new_globals.update(__file__=script_file)
exec(compile(open(script_file).read(), script_file, 'exec'),new_globals)